language: python
python:
  - "2.7"
  - "2.6"
before_install:
  - sh -c set
install: true
before_script: python misc/build_helpers/show-tool-versions.py
script: python setup.py test --reporter=timing
notifications:
  email: false
  irc:
    channels: "chat.freenode.net#tahoe-lafs"
    on_success: always # for testing
    on_failure: always
    template:
      - "%{repository}#%{build_number} [%{branch}: %{commit} by %{author}] %{message}"
      - "Changes: %{compare_url} | Details: %{build_url}"
